# Generated by Django 3.2.7 on 2021-11-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('items_json', models.CharField(max_length=5000)),
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
                ('address1', models.CharField(default='', max_length=30)),
                ('address2', models.CharField(default='', max_length=300)),
                ('phone', models.CharField(default='', max_length=10)),
                ('email', models.CharField(default='', max_length=30)),
                ('city', models.CharField(default='', max_length=30)),
                ('state', models.CharField(default='', max_length=30)),
                ('zipcode', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
